import { Product, Supplier } from "@/types/product";

const suppliers: Supplier[] = [
  {
    id: "s1", name: "TechSource Global", location: "Shenzhen, China",
    reliabilityScore: 92, shippingDays: 7, rating: 4.8, reviews: 12400,
    responseTime: "< 4 hours", trustBadge: "gold", orderCompletionRate: 98.5, disputeRate: 0.8,
  },
  {
    id: "s2", name: "PrimeDrop Fulfillment", location: "Los Angeles, US",
    reliabilityScore: 96, shippingDays: 3, rating: 4.9, reviews: 8200,
    responseTime: "< 2 hours", trustBadge: "gold", orderCompletionRate: 99.2, disputeRate: 0.3,
  },
  {
    id: "s3", name: "EuropaSupply", location: "Berlin, Germany",
    reliabilityScore: 88, shippingDays: 5, rating: 4.6, reviews: 5600,
    responseTime: "< 6 hours", trustBadge: "silver", orderCompletionRate: 97.1, disputeRate: 1.2,
  },
  {
    id: "s4", name: "CJ Direct", location: "Yiwu, China",
    reliabilityScore: 85, shippingDays: 10, rating: 4.5, reviews: 28000,
    responseTime: "< 8 hours", trustBadge: "silver", orderCompletionRate: 96.8, disputeRate: 1.8,
  },
  {
    id: "s5", name: "NordicTrade Co", location: "Stockholm, Sweden",
    reliabilityScore: 90, shippingDays: 4, rating: 4.7, reviews: 3200,
    responseTime: "< 3 hours", trustBadge: "gold", orderCompletionRate: 98.9, disputeRate: 0.5,
  },
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    title: "Wireless Bluetooth Earbuds Pro Max",
    description: "Active noise cancellation, 40hr battery life, IPX5 waterproof. Premium sound quality with deep bass and crystal-clear highs. Perfect for workouts and daily commute.",
    category: "Electronics",
    images: ["https://placehold.co/600x600/0f0f17/3b82f6?text=Earbuds+Pro", "https://placehold.co/600x600/0f0f17/3b82f6?text=Earbuds+Side", "https://placehold.co/600x600/0f0f17/3b82f6?text=Earbuds+Case"],
    platformPrices: [
      { platform: "Amazon", price: 34.99, url: "#", inStock: true, rating: 4.5, reviews: 12400 },
      { platform: "AliExpress", price: 8.50, url: "#", inStock: true, rating: 4.3, reviews: 45000 },
      { platform: "eBay", price: 22.99, url: "#", inStock: true, rating: 4.2, reviews: 3200 },
      { platform: "Walmart", price: 29.99, url: "#", inStock: false, rating: 4.4, reviews: 1800 },
    ],
    suppliers: [suppliers[0], suppliers[1], suppliers[3]],
    trending: true,
    riskScore: 32,
    profitPotential: "high",
    competitionLevel: "high",
    searchVolume: 89000,
    averageRating: 4.5,
    totalReviews: 62200,
    marketTrend: "rising",
    seasonality: "Year-round",
    tags: ["bluetooth", "earbuds", "wireless", "noise-cancelling", "fitness"],
  },
  {
    id: "p2",
    title: "Smart LED Strip Lights 10M RGB",
    description: "WiFi-enabled, app control, voice assistant compatible. 16 million colors, music sync, scheduling. Easy installation with strong adhesive backing.",
    category: "Home & Kitchen",
    images: ["https://placehold.co/600x600/0f0f17/a855f7?text=LED+Strip", "https://placehold.co/600x600/0f0f17/a855f7?text=LED+Room", "https://placehold.co/600x600/0f0f17/a855f7?text=LED+App"],
    platformPrices: [
      { platform: "Amazon", price: 19.99, url: "#", inStock: true, rating: 4.3, reviews: 28000 },
      { platform: "AliExpress", price: 4.20, url: "#", inStock: true, rating: 4.1, reviews: 89000 },
      { platform: "Walmart", price: 16.99, url: "#", inStock: true, rating: 4.2, reviews: 5400 },
    ],
    suppliers: [suppliers[0], suppliers[3], suppliers[4]],
    trending: true,
    riskScore: 28,
    profitPotential: "high",
    competitionLevel: "very-high",
    searchVolume: 145000,
    averageRating: 4.2,
    totalReviews: 122400,
    marketTrend: "stable",
    seasonality: "Year-round, peaks in holidays",
    tags: ["led", "smart-home", "rgb", "wifi", "decor"],
  },
  {
    id: "p3",
    title: "Posture Corrector Back Brace",
    description: "Medical-grade lumbar support, breathable mesh, adjustable straps. Clinically tested for pain relief. Suitable for office work and daily wear.",
    category: "Health & Wellness",
    images: ["https://placehold.co/600x600/0f0f17/22c55e?text=Posture+Brace", "https://placehold.co/600x600/0f0f17/22c55e?text=Brace+Back", "https://placehold.co/600x600/0f0f17/22c55e?text=Brace+Worn"],
    platformPrices: [
      { platform: "Amazon", price: 24.99, url: "#", inStock: true, rating: 4.6, reviews: 34000 },
      { platform: "AliExpress", price: 5.80, url: "#", inStock: true, rating: 4.4, reviews: 67000 },
      { platform: "eBay", price: 18.50, url: "#", inStock: true, rating: 4.3, reviews: 4100 },
    ],
    suppliers: [suppliers[0], suppliers[2], suppliers[3]],
    trending: false,
    riskScore: 22,
    profitPotential: "high",
    competitionLevel: "medium",
    searchVolume: 67000,
    averageRating: 4.5,
    totalReviews: 105100,
    marketTrend: "stable",
    seasonality: "Year-round",
    tags: ["health", "posture", "back-pain", "wellness", "office"],
  },
  {
    id: "p4",
    title: "Portable Espresso Maker Mini",
    description: "Hand-powered, no electricity needed. Makes real espresso anywhere. Stainless steel, BPA-free. Perfect for camping, travel, and office.",
    category: "Kitchen",
    images: ["https://placehold.co/600x600/0f0f17/f97316?text=Espresso+Maker", "https://placehold.co/600x600/0f0f17/f97316?text=Espresso+Pour", "https://placehold.co/600x600/0f0f17/f97316?text=Espresso+Pack"],
    platformPrices: [
      { platform: "Amazon", price: 29.99, url: "#", inStock: true, rating: 4.4, reviews: 8900 },
      { platform: "AliExpress", price: 12.50, url: "#", inStock: true, rating: 4.2, reviews: 15000 },
      { platform: "Walmart", price: 26.99, url: "#", inStock: true, rating: 4.3, reviews: 2100 },
    ],
    suppliers: [suppliers[0], suppliers[1], suppliers[4]],
    trending: true,
    riskScore: 35,
    profitPotential: "medium",
    competitionLevel: "medium",
    searchVolume: 34000,
    averageRating: 4.3,
    totalReviews: 26000,
    marketTrend: "rising",
    seasonality: "Peaks in summer",
    tags: ["coffee", "espresso", "portable", "travel", "kitchen"],
  },
  {
    id: "p5",
    title: "Magnetic Phone Mount Car Dashboard",
    description: "360-degree rotation, strong N52 magnets, one-hand operation. Compatible with all smartphones. Premium aluminum alloy construction.",
    category: "Automotive",
    images: ["https://placehold.co/600x600/0f0f17/eab308?text=Phone+Mount", "https://placehold.co/600x600/0f0f17/eab308?text=Mount+Car", "https://placehold.co/600x600/0f0f17/eab308?text=Mount+Detail"],
    platformPrices: [
      { platform: "Amazon", price: 14.99, url: "#", inStock: true, rating: 4.7, reviews: 56000 },
      { platform: "AliExpress", price: 2.80, url: "#", inStock: true, rating: 4.5, reviews: 120000 },
      { platform: "eBay", price: 9.99, url: "#", inStock: true, rating: 4.4, reviews: 7800 },
      { platform: "Walmart", price: 12.99, url: "#", inStock: true, rating: 4.6, reviews: 3400 },
    ],
    suppliers: [suppliers[0], suppliers[3], suppliers[4]],
    trending: false,
    riskScore: 18,
    profitPotential: "high",
    competitionLevel: "very-high",
    searchVolume: 112000,
    averageRating: 4.6,
    totalReviews: 187200,
    marketTrend: "stable",
    seasonality: "Year-round",
    tags: ["phone", "car", "mount", "magnetic", "accessories"],
  },
  {
    id: "p6",
    title: "Pet GPS Tracker Smart Collar",
    description: "Real-time tracking, geofencing alerts, activity monitoring. Waterproof IP67, 7-day battery. Works with iOS and Android app.",
    category: "Pet Supplies",
    images: ["https://placehold.co/600x600/0f0f17/06b6d4?text=GPS+Collar", "https://placehold.co/600x600/0f0f17/06b6d4?text=Collar+Dog", "https://placehold.co/600x600/0f0f17/06b6d4?text=Collar+App"],
    platformPrices: [
      { platform: "Amazon", price: 39.99, url: "#", inStock: true, rating: 4.3, reviews: 4200 },
      { platform: "AliExpress", price: 15.99, url: "#", inStock: true, rating: 4.1, reviews: 8900 },
      { platform: "eBay", price: 28.50, url: "#", inStock: true, rating: 4.2, reviews: 1100 },
    ],
    suppliers: [suppliers[0], suppliers[1], suppliers[2]],
    trending: true,
    riskScore: 40,
    profitPotential: "medium",
    competitionLevel: "low",
    searchVolume: 28000,
    averageRating: 4.2,
    totalReviews: 14200,
    marketTrend: "rising",
    seasonality: "Year-round",
    tags: ["pet", "gps", "tracker", "smart-collar", "dog"],
  },
  {
    id: "p7",
    title: "Minimalist Wallet RFID Blocking",
    description: "Genuine leather, slim design, holds 12 cards. RFID blocking technology prevents electronic theft. Gift box included.",
    category: "Fashion",
    images: ["https://placehold.co/600x600/0f0f17/8b5cf6?text=Wallet+Front", "https://placehold.co/600x600/0f0f17/8b5cf6?text=Wallet+Open", "https://placehold.co/600x600/0f0f17/8b5cf6?text=Wallet+Gift"],
    platformPrices: [
      { platform: "Amazon", price: 16.99, url: "#", inStock: true, rating: 4.5, reviews: 18000 },
      { platform: "AliExpress", price: 3.50, url: "#", inStock: true, rating: 4.3, reviews: 42000 },
      { platform: "Walmart", price: 14.99, url: "#", inStock: true, rating: 4.4, reviews: 2800 },
    ],
    suppliers: [suppliers[0], suppliers[3], suppliers[4]],
    trending: false,
    riskScore: 15,
    profitPotential: "high",
    competitionLevel: "high",
    searchVolume: 76000,
    averageRating: 4.4,
    totalReviews: 62800,
    marketTrend: "stable",
    seasonality: "Peaks in gift seasons",
    tags: ["wallet", "rfid", "leather", "minimalist", "gift"],
  },
  {
    id: "p8",
    title: "Yoga Mat Non-Slip Premium 6mm",
    description: "Eco-friendly TPE material, alignment lines, carrying strap included. Extra thick for joint protection. Perfect for yoga, pilates, and home workouts.",
    category: "Sports & Outdoors",
    images: ["https://placehold.co/600x600/0f0f17/ec4899?text=Yoga+Mat", "https://placehold.co/600x600/0f0f17/ec4899?text=Mat+Texture", "https://placehold.co/600x600/0f0f17/ec4899?text=Mat+Use"],
    platformPrices: [
      { platform: "Amazon", price: 22.99, url: "#", inStock: true, rating: 4.6, reviews: 15000 },
      { platform: "AliExpress", price: 6.90, url: "#", inStock: true, rating: 4.4, reviews: 32000 },
      { platform: "Walmart", price: 19.99, url: "#", inStock: true, rating: 4.5, reviews: 4500 },
    ],
    suppliers: [suppliers[0], suppliers[2], suppliers[3]],
    trending: false,
    riskScore: 20,
    profitPotential: "medium",
    competitionLevel: "medium",
    searchVolume: 52000,
    averageRating: 4.5,
    totalReviews: 51500,
    marketTrend: "stable",
    seasonality: "Peaks in January",
    tags: ["yoga", "fitness", "mat", "exercise", "eco-friendly"],
  },
];

export function getProductById(id: string): Product | undefined {
  return mockProducts.find((p) => p.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return mockProducts.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}
