import type { CountryCustomsData, HSCodeDutyRate } from "@/types/shipping";

// ── Shipping Zone Mapping ─────────────────────────────────────────────────────
// Zones determine shipping costs and delivery times based on origin→destination pairs

export const SHIPPING_ZONES: Record<string, string> = {
  CN: "asia_east",
  HK: "asia_east",
  TW: "asia_east",
  JP: "asia_east",
  KR: "asia_east",
  SG: "asia_southeast",
  TH: "asia_southeast",
  VN: "asia_southeast",
  MY: "asia_southeast",
  PH: "asia_southeast",
  ID: "asia_southeast",
  IN: "asia_south",
  PK: "asia_south",
  BD: "asia_south",
  LK: "asia_south",
  US: "north_america",
  CA: "north_america",
  MX: "north_america",
  GB: "europe_west",
  DE: "europe_west",
  FR: "europe_west",
  IT: "europe_west",
  ES: "europe_west",
  NL: "europe_west",
  BE: "europe_west",
  AT: "europe_west",
  IE: "europe_west",
  PT: "europe_west",
  SE: "europe_north",
  NO: "europe_north",
  DK: "europe_north",
  FI: "europe_north",
  PL: "europe_east",
  CZ: "europe_east",
  RO: "europe_east",
  HU: "europe_east",
  BG: "europe_east",
  HR: "europe_east",
  GR: "europe_south",
  TR: "europe_south",
  BR: "south_america",
  AR: "south_america",
  CL: "south_america",
  CO: "south_america",
  PE: "south_america",
  AU: "oceania",
  NZ: "oceania",
  ZA: "africa",
  NG: "africa",
  EG: "africa",
  KE: "africa",
  AE: "middle_east",
  SA: "middle_east",
  IL: "middle_east",
  QA: "middle_east",
};

export type ShippingZone = typeof SHIPPING_ZONES[keyof typeof SHIPPING_ZONES];

// ── Zone-to-Zone Shipping Multipliers ─────────────────────────────────────────
// Applied to base carrier rates for international shipping

export const ZONE_MULTIPLIERS: Record<string, Record<string, number>> = {
  asia_east: {
    asia_east: 1.0,
    asia_southeast: 1.1,
    asia_south: 1.15,
    north_america: 1.8,
    europe_west: 1.9,
    europe_north: 2.0,
    europe_east: 1.85,
    europe_south: 1.95,
    south_america: 2.2,
    oceania: 2.0,
    africa: 2.3,
    middle_east: 1.7,
  },
  asia_southeast: {
    asia_east: 1.1,
    asia_southeast: 1.0,
    asia_south: 1.1,
    north_america: 1.85,
    europe_west: 1.95,
    europe_north: 2.05,
    europe_east: 1.9,
    europe_south: 2.0,
    south_america: 2.25,
    oceania: 1.6,
    africa: 2.35,
    middle_east: 1.75,
  },
  north_america: {
    asia_east: 1.8,
    asia_southeast: 1.85,
    asia_south: 1.9,
    north_america: 1.0,
    europe_west: 1.5,
    europe_north: 1.55,
    europe_east: 1.45,
    europe_south: 1.55,
    south_america: 1.6,
    oceania: 1.7,
    africa: 1.8,
    middle_east: 1.6,
  },
  europe_west: {
    asia_east: 1.9,
    asia_southeast: 1.95,
    asia_south: 2.0,
    north_america: 1.5,
    europe_west: 1.0,
    europe_north: 1.1,
    europe_east: 1.15,
    europe_south: 1.1,
    south_america: 1.7,
    oceania: 1.8,
    africa: 1.6,
    middle_east: 1.3,
  },
};

// Fallback multiplier for zones not explicitly defined
const DEFAULT_ZONE_MULTIPLIER = 1.8;

// ── Country Customs Data ──────────────────────────────────────────────────────

export const COUNTRY_CUSTOMS_DATA: Record<string, CountryCustomsData> = {
  US: {
    countryCode: "US",
    countryName: "United States",
    currency: "USD",
    deMinimisThreshold: 800,
    deMinimisCurrency: "USD",
    vatRates: { standard: 0, reduced: [] },
    importDuty: {
      electronics: 0,
      clothing: 0.082,
      shoes: 0.10,
      bags: 0.08,
      jewelry: 0.05,
      toys: 0,
      home: 0.03,
      beauty: 0.02,
      default: 0.04,
    },
    prohibitedItems: ["narcotics", "weapons", "counterfeit goods", "obscene materials"],
    restrictedItems: ["food", "plants", "animals", "medications", "alcohol"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["De minimis threshold $800 per shipment", "FDA may review food/health products"],
  },
  GB: {
    countryCode: "GB",
    countryName: "United Kingdom",
    currency: "GBP",
    deMinimisThreshold: 135,
    deMinimisCurrency: "GBP",
    vatRates: { standard: 0.20, reduced: [0.05] },
    importDuty: {
      electronics: 0,
      clothing: 0.12,
      shoes: 0.08,
      bags: 0.08,
      jewelry: 0.04,
      toys: 0.047,
      home: 0.06,
      beauty: 0.06,
      default: 0.06,
    },
    prohibitedItems: ["narcotics", "weapons", "offensive weapons", "indecent material"],
    restrictedItems: ["food", "plants", "animals", "medications", "firearms"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["VAT collected at point of sale for consignments <=£135", "IOSS number required for EU sales"],
  },
  DE: {
    countryCode: "DE",
    countryName: "Germany",
    currency: "EUR",
    deMinimisThreshold: 150,
    deMinimisCurrency: "EUR",
    vatRates: { standard: 0.19, reduced: [0.07] },
    importDuty: {
      electronics: 0,
      clothing: 0.12,
      shoes: 0.169,
      bags: 0.097,
      jewelry: 0.025,
      toys: 0.047,
      home: 0.06,
      beauty: 0.065,
      default: 0.06,
    },
    prohibitedItems: ["narcotics", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications", "precious metals"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["IOSS for goods <=€150", "EORI number required for B2B"],
  },
  FR: {
    countryCode: "FR",
    countryName: "France",
    currency: "EUR",
    deMinimisThreshold: 150,
    deMinimisCurrency: "EUR",
    vatRates: { standard: 0.20, reduced: [0.055, 0.10] },
    importDuty: {
      electronics: 0,
      clothing: 0.12,
      shoes: 0.169,
      bags: 0.097,
      jewelry: 0.025,
      toys: 0.047,
      home: 0.06,
      beauty: 0.065,
      default: 0.06,
    },
    prohibitedItems: ["narcotics", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["Same EU customs rules as Germany", "Anti-counterfeiting laws strict"],
  },
  CA: {
    countryCode: "CA",
    countryName: "Canada",
    currency: "CAD",
    deMinimisThreshold: 20,
    deMinimisCurrency: "CAD",
    vatRates: { standard: 0.05, reduced: [] },
    importDuty: {
      electronics: 0,
      clothing: 0.18,
      shoes: 0.11,
      bags: 0.08,
      jewelry: 0.085,
      toys: 0.08,
      home: 0.09,
      beauty: 0.05,
      default: 0.08,
    },
    prohibitedItems: ["narcotics", "weapons", "hate propaganda"],
    restrictedItems: ["food", "plants", "animals", "drugs", "alcohol", "tobacco"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["GST + PST may apply", "Low de minimis threshold"],
  },
  AU: {
    countryCode: "AU",
    countryName: "Australia",
    currency: "AUD",
    deMinimisThreshold: 1000,
    deMinimisCurrency: "AUD",
    vatRates: { standard: 0.10, reduced: [] },
    importDuty: {
      electronics: 0,
      clothing: 0.05,
      shoes: 0.05,
      bags: 0.05,
      jewelry: 0.05,
      toys: 0.05,
      home: 0.05,
      beauty: 0.05,
      default: 0.05,
    },
    prohibitedItems: ["drugs", "weapons", "protected wildlife"],
    restrictedItems: ["food", "plants", "animals", "medications", "firearms"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["GST applies on all imports", "Biosecurity restrictions strict"],
  },
  JP: {
    countryCode: "JP",
    countryName: "Japan",
    currency: "JPY",
    deMinimisThreshold: 10000,
    deMinimisCurrency: "JPY",
    vatRates: { standard: 0.10, reduced: [] },
    importDuty: {
      electronics: 0,
      clothing: 0.10,
      shoes: 0.10,
      bags: 0.10,
      jewelry: 0.05,
      toys: 0.05,
      home: 0.05,
      beauty: 0.05,
      default: 0.05,
    },
    prohibitedItems: ["drugs", "weapons", "pornography"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["JCT (Japanese Consumption Tax) applies above threshold"],
  },
  BR: {
    countryCode: "BR",
    countryName: "Brazil",
    currency: "BRL",
    deMinimisThreshold: 50,
    deMinimisCurrency: "USD",
    vatRates: { standard: 0.17, reduced: [] },
    importDuty: {
      electronics: 0.16,
      clothing: 0.35,
      shoes: 0.35,
      bags: 0.20,
      jewelry: 0.15,
      toys: 0.20,
      home: 0.18,
      beauty: 0.22,
      default: 0.20,
    },
    prohibitedItems: ["drugs", "weapons", "used tires"],
    restrictedItems: ["food", "plants", "animals", "medications", "alcohol"],
    requiresCustomsForm: true,
    averageClearanceDays: 5,
    notes: ["Very high import duties", "ICMS state tax additional", "Complex customs process"],
  },
  IN: {
    countryCode: "IN",
    countryName: "India",
    currency: "INR",
    deMinimisThreshold: 50,
    deMinimisCurrency: "USD",
    vatRates: { standard: 0.18, reduced: [0.05, 0.12] },
    importDuty: {
      electronics: 0.20,
      clothing: 0.20,
      shoes: 0.25,
      bags: 0.20,
      jewelry: 0.15,
      toys: 0.20,
      home: 0.15,
      beauty: 0.20,
      default: 0.18,
    },
    prohibitedItems: ["drugs", "weapons", "pornography", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications", "electronics"],
    requiresCustomsForm: true,
    averageClearanceDays: 3,
    notes: ["IGST applies on imports", "BIS certification for electronics"],
  },
  AE: {
    countryCode: "AE",
    countryName: "United Arab Emirates",
    currency: "AED",
    deMinimisThreshold: 1000,
    deMinimisCurrency: "AED",
    vatRates: { standard: 0.05, reduced: [] },
    importDuty: {
      electronics: 0.05,
      clothing: 0.05,
      shoes: 0.05,
      bags: 0.05,
      jewelry: 0.05,
      toys: 0.05,
      home: 0.05,
      beauty: 0.05,
      default: 0.05,
    },
    prohibitedItems: ["drugs", "weapons", "alcohol", "pork products"],
    restrictedItems: ["food", "medications", "cosmetics"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["Low uniform duty rate", "VAT at 5%"],
  },
  SG: {
    countryCode: "SG",
    countryName: "Singapore",
    currency: "SGD",
    deMinimisThreshold: 400,
    deMinimisCurrency: "SGD",
    vatRates: { standard: 0.09, reduced: [] },
    importDuty: {
      electronics: 0,
      clothing: 0,
      shoes: 0,
      bags: 0,
      jewelry: 0,
      toys: 0,
      home: 0,
      beauty: 0,
      default: 0,
    },
    prohibitedItems: ["drugs", "weapons", "firecrackers"],
    restrictedItems: ["food", "animals", "medications", "tobacco"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["Most goods duty-free", "GST applies above threshold"],
  },
  KR: {
    countryCode: "KR",
    countryName: "South Korea",
    currency: "KRW",
    deMinimisThreshold: 150,
    deMinimisCurrency: "USD",
    vatRates: { standard: 0.10, reduced: [] },
    importDuty: {
      electronics: 0.08,
      clothing: 0.13,
      shoes: 0.13,
      bags: 0.08,
      jewelry: 0.08,
      toys: 0.08,
      home: 0.08,
      beauty: 0.08,
      default: 0.08,
    },
    prohibitedItems: ["drugs", "weapons", "pornography"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["VAT collected by customs", "KC certification for electronics"],
  },
  NL: {
    countryCode: "NL",
    countryName: "Netherlands",
    currency: "EUR",
    deMinimisThreshold: 150,
    deMinimisCurrency: "EUR",
    vatRates: { standard: 0.21, reduced: [0.09] },
    importDuty: {
      electronics: 0,
      clothing: 0.12,
      shoes: 0.169,
      bags: 0.097,
      jewelry: 0.025,
      toys: 0.047,
      home: 0.06,
      beauty: 0.065,
      default: 0.06,
    },
    prohibitedItems: ["drugs", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 1,
    notes: ["EU single market rules apply", "Major EU logistics hub"],
  },
  IT: {
    countryCode: "IT",
    countryName: "Italy",
    currency: "EUR",
    deMinimisThreshold: 150,
    deMinimisCurrency: "EUR",
    vatRates: { standard: 0.22, reduced: [0.04, 0.10] },
    importDuty: {
      electronics: 0,
      clothing: 0.12,
      shoes: 0.169,
      bags: 0.097,
      jewelry: 0.025,
      toys: 0.047,
      home: 0.06,
      beauty: 0.065,
      default: 0.06,
    },
    prohibitedItems: ["drugs", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["EU customs rules", "Stricter food import regulations"],
  },
  ES: {
    countryCode: "ES",
    countryName: "Spain",
    currency: "EUR",
    deMinimisThreshold: 150,
    deMinimisCurrency: "EUR",
    vatRates: { standard: 0.21, reduced: [0.04, 0.10] },
    importDuty: {
      electronics: 0,
      clothing: 0.12,
      shoes: 0.169,
      bags: 0.097,
      jewelry: 0.025,
      toys: 0.047,
      home: 0.06,
      beauty: 0.065,
      default: 0.06,
    },
    prohibitedItems: ["drugs", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["EU customs rules"],
  },
  SA: {
    countryCode: "SA",
    countryName: "Saudi Arabia",
    currency: "SAR",
    deMinimisThreshold: 1000,
    deMinimisCurrency: "SAR",
    vatRates: { standard: 0.15, reduced: [] },
    importDuty: {
      electronics: 0.05,
      clothing: 0.15,
      shoes: 0.15,
      bags: 0.10,
      jewelry: 0.05,
      toys: 0.05,
      home: 0.05,
      beauty: 0.05,
      default: 0.05,
    },
    prohibitedItems: ["drugs", "alcohol", "pork", "weapons", "pornography"],
    restrictedItems: ["food", "medications", "electronics"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["SABER certification for some goods", "VAT at 15%"],
  },
  ZA: {
    countryCode: "ZA",
    countryName: "South Africa",
    currency: "ZAR",
    deMinimisThreshold: 500,
    deMinimisCurrency: "ZAR",
    vatRates: { standard: 0.15, reduced: [] },
    importDuty: {
      electronics: 0.10,
      clothing: 0.22,
      shoes: 0.20,
      bags: 0.15,
      jewelry: 0.10,
      toys: 0.10,
      home: 0.10,
      beauty: 0.10,
      default: 0.10,
    },
    prohibitedItems: ["drugs", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 3,
    notes: ["VAT collected at customs", "ITU permit for some electronics"],
  },
  MX: {
    countryCode: "MX",
    countryName: "Mexico",
    currency: "MXN",
    deMinimisThreshold: 50,
    deMinimisCurrency: "USD",
    vatRates: { standard: 0.16, reduced: [] },
    importDuty: {
      electronics: 0.15,
      clothing: 0.20,
      shoes: 0.18,
      bags: 0.15,
      jewelry: 0.10,
      toys: 0.15,
      home: 0.15,
      beauty: 0.15,
      default: 0.15,
    },
    prohibitedItems: ["drugs", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["IVA tax applies on imports", "Low de minimis threshold"],
  },
  PL: {
    countryCode: "PL",
    countryName: "Poland",
    currency: "PLN",
    deMinimisThreshold: 150,
    deMinimisCurrency: "EUR",
    vatRates: { standard: 0.23, reduced: [0.05, 0.08] },
    importDuty: {
      electronics: 0,
      clothing: 0.12,
      shoes: 0.169,
      bags: 0.097,
      jewelry: 0.025,
      toys: 0.047,
      home: 0.06,
      beauty: 0.065,
      default: 0.06,
    },
    prohibitedItems: ["drugs", "weapons", "counterfeit goods"],
    restrictedItems: ["food", "plants", "animals", "medications"],
    requiresCustomsForm: true,
    averageClearanceDays: 2,
    notes: ["EU customs rules", "Growing e-commerce hub"],
  },
};

// ── Default Country Data ──────────────────────────────────────────────────────
const DEFAULT_COUNTRY_DATA: CountryCustomsData = {
  countryCode: "XX",
  countryName: "Unknown",
  currency: "USD",
  deMinimisThreshold: 200,
  deMinimisCurrency: "USD",
  vatRates: { standard: 0.15, reduced: [] },
  importDuty: { default: 0.10 },
  prohibitedItems: [],
  restrictedItems: [],
  requiresCustomsForm: true,
  averageClearanceDays: 3,
  notes: ["Default rates applied - verify for specific country"],
};

// ── HS Code Duty Rates ───────────────────────────────────────────────────────

export const HS_CODE_RATES: Record<string, HSCodeDutyRate> = {
  "8517": {
    hsCode: "8517",
    description: "Telephones & communication devices",
    dutyRate: 0,
    vatRate: 0.20,
    restricted: false,
    notes: "Often duty-free for electronic communication devices",
  },
  "8518": {
    hsCode: "8518",
    description: "Headphones, earphones, speakers",
    dutyRate: 0,
    vatRate: 0.20,
    restricted: false,
    notes: "Common for wireless earbuds and audio equipment",
  },
  "8528": {
    hsCode: "8528",
    description: "Monitors, projectors, displays",
    dutyRate: 0,
    vatRate: 0.20,
    restricted: false,
    notes: "TVs and display monitors",
  },
  "6110": {
    hsCode: "6110",
    description: "Jerseys, sweaters, pullovers (knitted)",
    dutyRate: 0.12,
    vatRate: 0.20,
    restricted: false,
    notes: "Knitted clothing items",
  },
  "6104": {
    hsCode: "6104",
    description: "Women's suits, dresses (knitted)",
    dutyRate: 0.12,
    vatRate: 0.20,
    restricted: false,
    notes: "Women's knitted apparel",
  },
  "6403": {
    hsCode: "6403",
    description: "Footwear with leather uppers",
    dutyRate: 0.169,
    vatRate: 0.20,
    restricted: false,
    notes: "Leather shoes and boots",
  },
  "6402": {
    hsCode: "6402",
    description: "Footwear with rubber/plastic uppers",
    dutyRate: 0.169,
    vatRate: 0.20,
    restricted: false,
    notes: "Rubber or plastic footwear",
  },
  "4202": {
    hsCode: "4202",
    description: "Bags, cases, wallets",
    dutyRate: 0.097,
    vatRate: 0.20,
    restricted: false,
    notes: "Handbags, wallets, travel bags",
  },
  "9503": {
    hsCode: "9503",
    description: "Toys, puzzles, models",
    dutyRate: 0.047,
    vatRate: 0.20,
    restricted: false,
    notes: "Children's toys and games",
  },
  "9506": {
    hsCode: "9506",
    description: "Sports equipment",
    dutyRate: 0.047,
    vatRate: 0.20,
    restricted: false,
    notes: "Sporting goods and equipment",
  },
  "3304": {
    hsCode: "3304",
    description: "Beauty / cosmetic preparations",
    dutyRate: 0.065,
    vatRate: 0.20,
    restricted: true,
    notes: "May require FDA/CPNP registration",
  },
  "3004": {
    hsCode: "3004",
    description: "Medicaments (packaged for retail)",
    dutyRate: 0.04,
    vatRate: 0.20,
    restricted: true,
    notes: "Requires pharmaceutical registration",
  },
  "8471": {
    hsCode: "8471",
    description: "Computers, laptops, tablets",
    dutyRate: 0,
    vatRate: 0.20,
    restricted: false,
    notes: "IT equipment often duty-free",
  },
  "7113": {
    hsCode: "7113",
    description: "Jewelry of precious metal",
    dutyRate: 0.025,
    vatRate: 0.20,
    restricted: false,
    notes: "Gold, silver, platinum jewelry",
  },
  "3926": {
    hsCode: "3926",
    description: "Plastic articles (general)",
    dutyRate: 0.06,
    vatRate: 0.20,
    restricted: false,
    notes: "General plastic products",
  },
  "7013": {
    hsCode: "7013",
    description: "Glassware for table/kitchen",
    dutyRate: 0.06,
    vatRate: 0.20,
    restricted: false,
    notes: "Glass cups, vases, decorative items",
  },
  "9405": {
    hsCode: "9405",
    description: "Lamps, lighting fittings",
    dutyRate: 0.047,
    vatRate: 0.20,
    restricted: false,
    notes: "LED lamps, decorative lighting",
  },
  "8516": {
    hsCode: "8516",
    description: "Electric water/space heaters, hair dryers",
    dutyRate: 0.022,
    vatRate: 0.20,
    restricted: false,
    notes: "Small electric heating appliances",
  },
  "7321": {
    hsCode: "7321",
    description: "Stoves, cookers, barbecues",
    dutyRate: 0.022,
    vatRate: 0.20,
    restricted: false,
    notes: "Gas/electric cooking appliances",
  },
};

// ── Helper Functions ──────────────────────────────────────────────────────────

export function getCountryData(countryCode: string): CountryCustomsData {
  return COUNTRY_CUSTOMS_DATA[countryCode.toUpperCase()] || { ...DEFAULT_COUNTRY_DATA, countryCode: countryCode.toUpperCase() };
}

export function getZone(originCountry: string, destinationCountry: string): number {
  const originZone = SHIPPING_ZONES[originCountry.toUpperCase()];
  const destZone = SHIPPING_ZONES[destinationCountry.toUpperCase()];
  if (!originZone || !destZone) return DEFAULT_ZONE_MULTIPLIER;
  const zoneData = ZONE_MULTIPLIERS[originZone];
  if (!zoneData) return DEFAULT_ZONE_MULTIPLIER;
  return zoneData[destZone] || DEFAULT_ZONE_MULTIPLIER;
}

export function getHSCodeRate(hsCode: string): HSCodeDutyRate | null {
  return HS_CODE_RATES[hsCode] || null;
}

export function isSameCountry(a: string, b: string): boolean {
  return a.toUpperCase() === b.toUpperCase();
}

export function getSupportedCountries(): string[] {
  return Object.keys(COUNTRY_CUSTOMS_DATA);
}

export function getCategoryDutyRate(countryCode: string, category: string): number {
  const data = getCountryData(countryCode);
  return data.importDuty[category] ?? data.importDuty["default"] ?? 0.10;
}

export function isProhibited(countryCode: string, item: string): boolean {
  const data = getCountryData(countryCode);
  return data.prohibitedItems.some((p) => item.toLowerCase().includes(p));
}

export function isRestricted(countryCode: string, item: string): boolean {
  const data = getCountryData(countryCode);
  return data.restrictedItems.some((r) => item.toLowerCase().includes(r));
}
