import type { CalculatorCategoryMeta } from "@/types/calculator";

export const calculatorCategories: CalculatorCategoryMeta[] = [
  {
    id: "profit-pricing",
    label: "Profit & Pricing",
    description: "Calculate margins, break-even points, and optimal pricing",
    icon: "DollarSign",
    color: "#10b981",
    calculators: [
      {
        id: "profit",
        label: "Profit Calculator",
        description: "Quick profit calculation with cost breakdown and revenue projections",
        icon: "DollarSign",
        href: "/calculator/profit",
        category: "profit-pricing",
      },
      {
        id: "margin",
        label: "Margin Calculator",
        description: "Find the right selling price for your desired profit margin",
        icon: "Percent",
        href: "/calculator/margin",
        category: "profit-pricing",
      },
      {
        id: "break-even",
        label: "Break-Even Calculator",
        description: "Find out how many orders you need to cover fixed and variable costs",
        icon: "Target",
        href: "/calculator/break-even",
        category: "profit-pricing",
        isNew: true,
      },
    ],
  },
  {
    id: "shipping-logistics",
    label: "Shipping & Logistics",
    description: "Estimate shipping costs, landed duties, and customs fees",
    icon: "Truck",
    color: "#f97316",
    calculators: [
      {
        id: "shipping",
        label: "Shipping Calculator",
        description: "Compare carrier costs by package size, weight, and destination",
        icon: "Truck",
        href: "/calculator/shipping",
        category: "shipping-logistics",
      },
      {
        id: "landed-cost",
        label: "Landed Cost Calculator",
        description: "Full import cost including tariffs, customs, and insurance",
        icon: "Globe",
        href: "/calculator/landed-cost",
        category: "shipping-logistics",
      },
      {
        id: "customs",
        label: "Customs & Import Duty",
        description: "HS code lookup, duty rates, VAT, and de minimis thresholds by country",
        icon: "FileSearch",
        href: "/calculator/customs",
        category: "shipping-logistics",
        isNew: true,
      },
    ],
  },
  {
    id: "advertising",
    label: "Advertising",
    description: "Measure ad ROI, ROAS, and the true cost of returns",
    icon: "Megaphone",
    color: "#a855f7",
    calculators: [
      {
        id: "ad-roi",
        label: "Ad ROI / ROAS Calculator",
        description: "Estimate CAC, break-even ROAS, and scaling scenarios",
        icon: "TrendingUp",
        href: "/calculator/ad-roi",
        category: "advertising",
        isNew: true,
      },
      {
        id: "returns",
        label: "Return & Refund Costs",
        description: "Calculate the true cost of product returns on your margins",
        icon: "RotateCcw",
        href: "/calculator/returns",
        category: "advertising",
        isNew: true,
      },
    ],
  },
  {
    id: "platform-specific",
    label: "Platform-Specific",
    description: "Compare marketplace fees and calculate Amazon FBA costs",
    icon: "Store",
    color: "#3b82f6",
    calculators: [
      {
        id: "amazon-fba",
        label: "Amazon FBA Calculator",
        description: "FBA fulfillment fees, storage, referral fees, and FBA vs FBM comparison",
        icon: "Package",
        href: "/calculator/amazon-fba",
        category: "platform-specific",
        isNew: true,
      },
      {
        id: "platform-comparison",
        label: "Platform Fee Comparison",
        description: "Compare Shopify, Amazon, eBay, Etsy, Walmart, and WooCommerce fees",
        icon: "BarChart3",
        href: "/calculator/platform-comparison",
        category: "platform-specific",
        isNew: true,
      },
    ],
  },
];
